version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      charm:
        patterns:
          - "charm.land/*"
          - "github.com/charmbracelet/*"
      nats:
        patterns:
          - "github.com/nats-io/*"
